import { useNavigate } from 'react-router-dom'
import { Logo } from '../components/Logo'
import { useIsMobile } from '../hooks/useIsMobile'

const LAST_UPDATED = 'June 13, 2025'
const CONTACT_EMAIL = 'legal@airesumestudio.com'

interface SectionProps {
  title: string
  children: React.ReactNode
}

function Section({ title, children }: SectionProps) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{
        fontSize: 18, fontWeight: 800, color: 'var(--navy)',
        marginBottom: 12, paddingBottom: 10,
        borderBottom: '2px solid var(--gray-100)',
      }}>
        {title}
      </h2>
      <div style={{ fontSize: 15, color: 'var(--charcoal)', lineHeight: 1.8 }}>
        {children}
      </div>
    </section>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ marginBottom: 12 }}>{children}</p>
}

function Ul({ items }: { items: string[] }) {
  return (
    <ul style={{ paddingLeft: 20, marginBottom: 12 }}>
      {items.map((item, i) => (
        <li key={i} style={{ marginBottom: 6 }}>{item}</li>
      ))}
    </ul>
  )
}

export function TermsPage() {
  const navigate = useNavigate()
  const isMobile = useIsMobile()

  return (
    <div style={{ minHeight: '100vh', background: 'var(--gray-50)', fontFamily: 'var(--font-sans)' }}>
      {/* Nav */}
      <nav style={{
        background: 'white', borderBottom: '1px solid var(--gray-100)',
        padding: '0 24px', height: 64, display: 'flex', alignItems: 'center',
        justifyContent: 'space-between', position: 'sticky', top: 0, zIndex: 100,
        boxShadow: 'var(--shadow-sm)',
      }}>
        <Logo size="sm" />
        <button
          onClick={() => navigate(-1)}
          style={{
            fontSize: 13, color: 'var(--gray-500)', fontWeight: 600,
            cursor: 'pointer', border: 'none', background: 'none',
            display: 'flex', alignItems: 'center', gap: 6,
          }}
        >
          ← Back
        </button>
      </nav>

      {/* Content */}
      <div style={{
        maxWidth: 760, margin: '0 auto',
        padding: isMobile ? '32px 20px 60px' : '48px 24px 80px',
      }}>
        {/* Header */}
        <div style={{ marginBottom: 40 }}>
          <h1 style={{
            fontSize: isMobile ? 28 : 36, fontWeight: 900,
            color: 'var(--navy)', letterSpacing: '-0.02em', marginBottom: 8,
          }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, color: 'var(--gray-400)' }}>
            Last updated: {LAST_UPDATED}
          </p>
          <div style={{
            marginTop: 20, padding: '14px 18px',
            background: '#EFF6FF', borderRadius: 'var(--radius)',
            border: '1px solid #BFDBFE',
            fontSize: 14, color: 'var(--charcoal)', lineHeight: 1.6,
          }}>
            <strong>The short version:</strong> Use the Service honestly, pay for Pro features if
            you want them, don't upload other people's resumes without their consent, and understand
            that AI-generated content is a tool — not professional career advice.
          </div>
        </div>

        <Section title="1. Acceptance of Terms">
          <P>
            By accessing or using AI Resume Studio (the "Service"), you agree to be bound by these
            Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.
          </P>
          <P>
            These Terms constitute a binding legal agreement between you and AI Resume Studio,
            operated from Trinidad and Tobago. By creating an account, you confirm that you are at
            least 16 years of age and have the legal capacity to enter into this agreement.
          </P>
        </Section>

        <Section title="2. Description of Service">
          <P>
            AI Resume Studio provides AI-powered tools to help job seekers improve their resumes,
            including:
          </P>
          <Ul items={[
            'ATS (Applicant Tracking System) compatibility scoring',
            'AI resume optimization and rewriting suggestions',
            'Cover letter generation',
            'LinkedIn headline and About section optimization',
            'PDF resume download in multiple templates',
          ]} />
          <P>
            The Service is powered by Anthropic's Claude AI. Results are generated by AI and
            intended as suggestions — they are not a guarantee of employment outcomes.
          </P>
        </Section>

        <Section title="3. Account Registration">
          <P>
            To access most features, you must create an account with a valid email address and
            password. You are responsible for:
          </P>
          <Ul items={[
            'Keeping your login credentials confidential',
            'All activity that occurs under your account',
            'Notifying us immediately at ' + CONTACT_EMAIL + ' if you suspect unauthorized access',
          ]} />
          <P>
            You may only create one account per person. Accounts may not be shared, sold, or
            transferred.
          </P>
        </Section>

        <Section title="4. Subscription Plans and Payments">
          <P>
            AI Resume Studio offers the following plans:
          </P>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14, marginBottom: 16 }}>
              <thead>
                <tr style={{ background: 'var(--gray-50)', textAlign: 'left' }}>
                  {['Plan', 'Price', 'Features'].map(h => (
                    <th key={h} style={{ padding: '10px 14px', fontWeight: 700, color: 'var(--navy)', borderBottom: '2px solid var(--gray-200)' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {[
                  ['Free', '$0 / forever', 'ATS scan, keyword gap analysis, score breakdown'],
                  ['Pro Monthly', '$19 / month', 'Everything free + AI optimization, cover letter, LinkedIn, PDF download'],
                  ['Pro One-Time', '$49 lifetime', 'All Pro features, no recurring charge'],
                ].map(([plan, price, features], i) => (
                  <tr key={i} style={{ borderBottom: '1px solid var(--gray-100)' }}>
                    <td style={{ padding: '10px 14px', fontWeight: 600 }}>{plan}</td>
                    <td style={{ padding: '10px 14px', color: 'var(--gray-600)' }}>{price}</td>
                    <td style={{ padding: '10px 14px', color: 'var(--gray-600)' }}>{features}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <P>
            <strong>Billing:</strong> Pro Monthly subscriptions are billed monthly via Stripe.
            Your subscription renews automatically until cancelled. You can cancel at any time
            through your account settings; access to Pro features continues until the end of the
            current billing period.
          </P>
          <P>
            <strong>Refunds:</strong> We offer a 7-day refund on monthly subscriptions if you are
            not satisfied with the Service. One-time lifetime purchases are non-refundable after
            14 days. To request a refund, email {CONTACT_EMAIL}.
          </P>
          <P>
            <strong>Price changes:</strong> We may change pricing at any time. We will give you at
            least 30 days' notice before applying any price increase to an active subscription.
          </P>
        </Section>

        <Section title="5. Acceptable Use">
          <P>You agree to use the Service only for lawful purposes. You must not:</P>
          <Ul items={[
            'Upload a resume belonging to another person without their explicit written consent',
            'Use the Service to generate misleading, fraudulent, or fabricated career credentials',
            'Attempt to reverse-engineer, scrape, or extract data from the Service by automated means',
            'Attempt to circumvent rate limits, authentication, or subscription gates',
            'Upload content that is defamatory, obscene, or infringes on a third party\'s intellectual property rights',
            'Use the Service in any way that violates applicable local or international law',
          ]} />
          <P>
            We reserve the right to suspend or terminate accounts that violate these terms without
            prior notice.
          </P>
        </Section>

        <Section title="6. AI-Generated Content Disclaimer">
          <P>
            The resume optimizations, cover letters, LinkedIn suggestions, and ATS scores produced
            by our Service are generated by artificial intelligence. You acknowledge that:
          </P>
          <Ul items={[
            'AI-generated content may contain errors, omissions, or suggestions that are not appropriate for your specific situation',
            'ATS scores are estimates based on keyword analysis and AI assessment — they are not a guarantee of how any particular employer\'s system will evaluate your resume',
            'Optimized resume text is a starting point for your own review and editing — you are responsible for the final content you submit to employers',
            'The Service does not constitute professional career coaching, legal advice, or employment advice',
            'We do not guarantee that using the Service will result in job interviews or employment offers',
          ]} />
          <P>
            Always review AI-generated content carefully before using it in a job application.
            Never submit a resume claiming experiences, qualifications, or credentials you do not
            actually have.
          </P>
        </Section>

        <Section title="7. Intellectual Property">
          <P>
            <strong>Your content:</strong> You retain full ownership of your resume, career history,
            and any content you upload to the Service. By uploading content, you grant us a
            limited, non-exclusive licence to process it solely to provide the Service to you.
            We do not claim ownership of your data.
          </P>
          <P>
            <strong>Our content:</strong> The AI Resume Studio platform, including its design,
            code, branding, and UI, is owned by AI Resume Studio and protected by intellectual
            property law. You may not copy, reproduce, or create derivative works from any part
            of the Service without our written permission.
          </P>
          <P>
            <strong>AI output:</strong> The resume text and other content generated by our AI for
            you is provided for your personal use. You may use, edit, and submit AI-generated
            content in your job applications. We make no warranty about the originality of
            AI-generated text.
          </P>
        </Section>

        <Section title="8. Privacy">
          <P>
            Your use of the Service is also governed by our{' '}
            <span
              onClick={() => window.location.href = '/privacy'}
              style={{ color: 'var(--navy)', fontWeight: 600, cursor: 'pointer' }}
            >
              Privacy Policy
            </span>
            , which is incorporated into these Terms by reference.
          </P>
        </Section>

        <Section title="9. Limitation of Liability">
          <P>
            To the fullest extent permitted by applicable law, AI Resume Studio and its operators
            shall not be liable for any indirect, incidental, special, consequential, or punitive
            damages, including but not limited to:
          </P>
          <Ul items={[
            'Loss of employment opportunities or income',
            'Errors in AI-generated resume content that affect a job application',
            'Service downtime or interruptions',
            'Unauthorized access to your account by third parties',
            'Data loss due to technical failure',
          ]} />
          <P>
            Our total liability to you for any claim arising out of or relating to the Service
            shall not exceed the amount you paid us in the 12 months preceding the claim, or
            USD $100, whichever is greater.
          </P>
        </Section>

        <Section title="10. Disclaimer of Warranties">
          <P>
            The Service is provided "as is" and "as available" without warranties of any kind,
            express or implied, including warranties of merchantability, fitness for a particular
            purpose, or non-infringement. We do not warrant that the Service will be uninterrupted,
            error-free, or that defects will be corrected.
          </P>
        </Section>

        <Section title="11. Termination">
          <P>
            <strong>By you:</strong> You may close your account at any time by contacting us at{' '}
            {CONTACT_EMAIL}. Closing your account cancels any active subscription at the end of
            the current billing period.
          </P>
          <P>
            <strong>By us:</strong> We may suspend or terminate your account immediately if you
            violate these Terms, engage in fraudulent activity, or if we are required to do so
            by law. We will give reasonable notice where possible.
          </P>
          <P>
            Upon termination, your right to use the Service ends. We will delete your personal
            data within 30 days of account closure, except where retention is required by law.
          </P>
        </Section>

        <Section title="12. Governing Law and Dispute Resolution">
          <P>
            These Terms are governed by and construed in accordance with the laws of{' '}
            <strong>the Republic of Trinidad and Tobago</strong>, without regard to its conflict
            of law provisions.
          </P>
          <P>
            Any dispute arising from these Terms or your use of the Service shall first be
            attempted to be resolved through good-faith negotiation. If we cannot resolve the
            dispute informally within 30 days, either party may refer the matter to the courts
            of Trinidad and Tobago, which shall have exclusive jurisdiction.
          </P>
        </Section>

        <Section title="13. Changes to These Terms">
          <P>
            We may update these Terms from time to time. We will notify registered users of
            material changes via email at least 14 days before they take effect. Continued use
            of the Service after the effective date constitutes acceptance of the updated Terms.
          </P>
          <P>
            If you do not agree to the updated Terms, you must stop using the Service and may
            close your account.
          </P>
        </Section>

        <Section title="14. Contact Us">
          <P>
            Questions about these Terms? Contact us:
          </P>
          <div style={{
            background: 'white', borderRadius: 'var(--radius)', padding: '20px 24px',
            border: '1px solid var(--gray-100)', boxShadow: 'var(--shadow-sm)',
          }}>
            <p style={{ fontWeight: 700, color: 'var(--navy)', marginBottom: 6 }}>AI Resume Studio</p>
            <p style={{ color: 'var(--gray-600)', fontSize: 14, lineHeight: 1.7 }}>
              Trinidad and Tobago<br />
              Email:{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: 'var(--navy)', fontWeight: 600 }}>
                {CONTACT_EMAIL}
              </a>
            </p>
          </div>
        </Section>
      </div>

      {/* Footer */}
      <footer style={{ background: 'var(--navy-dark)', padding: '28px 20px', textAlign: 'center' }}>
        <p style={{ color: 'rgba(255,255,255,0.35)', fontSize: 13 }}>
          © {new Date().getFullYear()} AI Resume Studio. All rights reserved.
        </p>
      </footer>
    </div>
  )
}
