/**
 * =========================================================
 * COMMON SHARED SCHEMA TYPES
 * =========================================================
 *
 * This file contains reusable shared interfaces that are
 * used across multiple entities in the platform.
 *
 * These structures help standardize:
 *
 * - issue reporting
 * - recommendation output
 * - AI generation metadata
 *
 * IMPORTANT:
 *
 * We do not want random, inconsistent JSON blobs being
 * stored in analysis fields.
 *
 * This file provides a controlled structure so the system
 * stays explainable and maintainable.
 *
 * =========================================================
 */

import {
  SeverityLevel,
  PriorityLevel,
  GenerationMode,
} from './enums';

import { ISODateTime } from './primitives';


/**
 * ---------------------------------------------------------
 * ISSUE ITEM
 * ---------------------------------------------------------
 *
 * Represents a detected problem found during analysis.
 *
 * Examples:
 * - missing measurable achievements
 * - weak keyword coverage
 * - missing contact information
 * - poor section completeness
 */
export interface IssueItem {
  code: string;
  severity: SeverityLevel;
  message: string;
  targetSection?: string;
  suggestedAction?: string;
}


/**
 * ---------------------------------------------------------
 * RECOMMENDATION ITEM
 * ---------------------------------------------------------
 *
 * Represents a suggested improvement generated by the
 * system.
 *
 * This should be used for structured feedback that the UI
 * and future analytics can understand.
 */
export interface RecommendationItem {
  code: string;
  priority: PriorityLevel;
  title: string;
  description: string;
  targetSection?: string;
}


/**
 * ---------------------------------------------------------
 * GENERATION METADATA
 * ---------------------------------------------------------
 *
 * Captures lightweight provenance for content created by
 * the system.
 *
 * This helps with:
 * - debugging
 * - quality assurance
 * - future model comparisons
 *
 * NOTE:
 * This is not a full audit log. It is just enough metadata
 * to understand how a version was created.
 */
export interface GenerationMetadata {
  mode?: GenerationMode;
  model?: string;
  promptVersion?: string;
  generatedAt?: ISODateTime;
}


/**
 * ---------------------------------------------------------
 * RULES TRIGGERED MAP
 * ---------------------------------------------------------
 *
 * Represents deterministic checks triggered during a scan.
 *
 * Example:
 * {
 *   missing_metrics_in_bullets: true,
 *   missing_target_keywords: true
 * }
 */
export type RulesTriggeredMap = Record<string, boolean>;